x-postgis_defaults: &postgis_defaults
  environment:
    - POSTGRES_PASSWORD
    - TZ
  restart: always
  
services:
   
  pg17:
    << : *postgis_defaults
    image: postgis/postgis:17-3.4
    container_name: pg17
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /run/postgresql:/run/postgresql
      - ./data/postgresql/17:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5433


  pg16:
    << : *postgis_defaults
    image: postgis/postgis:16-3.4
    container_name: pg16
    restart: always
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /run/postgresql:/run/postgresql
      - ./data/postgresql/16:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
